### ISSUE TITLE
Error\ "ImportError: bad magic number in 'model': b'\ x03\ xf3\ r\ n'\" when running test1.py

### ISSUE THREAD

**Issue by zhuiyiGitHub** [wgcban/SPIN_RoadMapper#1]

**Comment by zhuiyiGitHub** [comment]
Error\ "ImportError: bad magic number in 'model': b'\ x03\ xf3\ r\ n'\" when running test1.py

**Comment by wgcban** [comment]
Hi,
You can find an answer to your problem here:
https://stackoverflow.com/questions/52477683/importerror-bad-magic-number-in-time-b-x03-xf3-r-n-in-django

**Comment by zhuiyiGitHub** [comment]
hi，I ran this command following the link you gave me：“find . -name \*.pyc -delete ”, and the program reported an error "ModuleNotFoundError: No module named 'model.models'". How can I find this file
