### ISSUE TITLE
request for .pth weight file

### ISSUE THREAD

**Issue by XinlingQiu** [wgcban/SPIN_RoadMapper#2]
Hi! I train your algorithm, but cannot get a nice result.Could you share your weight file?Thanks a lot.

**Comment by wgcban** [comment]
Hi @XinlingQiu 

Please see the demo sections in the readme file to find out the links to pre-trained models.

Best 
Chaminda

**Comment by wgcban** [comment]
@XinlingQiu 
Unfortunately, I do not have the pre-trained model on DeepGlobe dataset right now. However, you can download the pre-trained model on Massachusets Road dataset by [this link](https://www.dropbox.com/sh/ymjyu2k7k85czge/AACSaxo6U4q9dHW1NBh6wCuga?dl=0).
