### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by patriksabol** [wgcban/SPIN_RoadMapper#5]
Hi @wgcban,
it seems some of the module and files are missing, such as
from model.models import MODELS
from utils.loss import CrossEntropyLoss2d, mIoULoss
without them I cannot run training nor testing.

Could you also share some trained model?

Many thanks

**Comment by cam1271** [comment]
I am not the author, but it seems all of the necessary functions are trapped in the pyc files.

**Comment by zzuilcc** [comment]
> 

作者少上传文件了

**Comment by londumas** [comment]
up ?

> I am not the author, but it seems all of the necessary functions are trapped in the pyc files.

including *pyc in a repo is bad practice, normally these are flagged in the .gitignore.

**Comment by jdilger** [comment]
Im not able to access `models` via the .pyc file.
```
from model.models import MODELS
> ImportError: bad magic number in 'model': b'\x03\xf3\r\n'
```

**Comment by wgcban** [comment]
Updated all the missing files ....
